# Generated by Django 5.2.7 on 2025-11-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='建立日期'),
        ),
    ]
